[project]
name = "mcp-github-pr-issue-analyser"
version = "2.5.0"
description = "MCP GitHub Issues Create/Update and PR Analyse"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "saidsef" }
]
dependencies = [
    "mcp[cli]==1.12.2",
    "requests==2.32.4",
    "uv==0.8.8",
]

[project.scripts]
mcp-github-pr-issue-analyser = "mcp_github.issues_pr_analyser:main"

[project.urls]
homepage = "https://github.com/saidsef/mcp-github-pr-issue-analyser"
issues = "https://github.com/saidsef/mcp-github-pr-issue-analyser/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
