[project]
name = "mcp-github-pr-issue-analyser"
version = "0.3.2"
description = "MCP GitHub Issues Create/Update and PR Analyse"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.8.0",
    "requests>=2.32.3",
]
