[project]
name = "mcp-github-pr-issue-analyser"
version = "1.0.1"
description = "MCP GitHub Issues Create/Update and PR Analyse"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.8.1,<2.0.0",
    "requests==2.32.3",
    "uv==0.7.5",
]
