[project]
name = "mcp-github-pr-issue-analyser"
version = "2.0.1"
description = "MCP GitHub Issues Create/Update and PR Analyse"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "saidsef"}
]
dependencies = [
    "mcp[cli]==1.8.1",
    "requests==2.32.3",
]

[project.scripts]
mcp-github-pr-issue-analyser = "src.issues_pr_analyser:main"

[project.urls]
Homepage = "https://github.com/saidsef/mcp-github-pr-issue-analyser"
Issues = "https://github.com/saidsef/mcp-github-pr-issue-analyser/issues"

[tool.setuptools]
[tool.setuptools.packages.find]
where = ["src"]  # Look in the src directory
include = ["*"]  # Include all packages/modules in src

[build-system]
requires = ["setuptools>=61.0","uv>=0.7.6"]
build-backend = "setuptools.build_meta"
