---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-github
  labels:
    app.kubernete.io/name: mcp-github
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernete.io/name: mcp-github
  template:
    metadata:
      labels:
        app.kubernete.io/name: mcp-github
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        filter.by.port.name: "true"
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      serviceAccountName: mcp-github
      containers:
      - name: mcp-github
        image: ghcr.io/saidsef/mcp-github-pr-issue-analyser:latest
        imagePullPolicy: Always
        env:
        - name : HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
              optional: true
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 150m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 10000
          runAsUser: 10000
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - name: data
            mountPath: /tmp
            subPath: tmp
            readOnly: false
          - name: data
            mountPath: /.cache
            subPath: cache
            readOnly: false
          - name: data
            mountPath: /app/.venv
            subPath: venv
            readOnly: false
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 1Gi
